version: '3.6'
volumes:
  service-discovery-logs:
  gateway-logs:
  product-api-logs:
services:
  service-discovery:
    build:
      context: ./service-discovery
    container_name: service-discovery
    restart: unless-stopped
    ports:
      - 8761:8761
    volumes:
      - service-discovery-logs:/logs
  gateway:
    build:
      context: ./gateway
    container_name: gateway
    restart: unless-stopped
    ports:
      - 8080:8080
    volumes:
      - gateway-logs:/logs
    depends_on:
      - service-discovery
  product-api:
    build:
      context: ./product-api
    container_name: product-api
    restart: unless-stopped
    ports:
      - 8090
    volumes:
      - product-api-logs:/logs
    depends_on:
      - service-discovery
      - gateway

    