spring:
  application:
    name: product-api
server:
  port: 0 # Random port

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER_URI:http://192.168.99.100:8761/eureka} # IP for Docker Toolbox
  instance:
    preferIpAddress: true